#!/usr/bin/env node
'use strict';
// Rebuilds the knowledge-base index. Run this after adding or editing any
// knowledge/<slug>.md entry:  node knowledge/build-index.cjs
//
// It writes two things:
//   knowledge/_index.json   -> machine index (keywords + doc-frequency) read by recall.cjs
//   docs/INTEGRATIONS.md     -> slim, human-browsable table of contents (AUTO-GENERATED)
//
// No dependencies. Never edit docs/INTEGRATIONS.md by hand -- edit the entries.

const fs = require('fs');
const path = require('path');

const KB_DIR = __dirname;
const REPO_ROOT = path.resolve(KB_DIR, '..');
const INDEX_JSON = path.join(KB_DIR, '_index.json');
const HUMAN_INDEX = path.join(REPO_ROOT, 'docs', 'INTEGRATIONS.md');

const norm = (s) => String(s == null ? '' : s).toLowerCase();

// --- tiny YAML-ish frontmatter parser (scalars + [a, b, c] arrays) ---
function parseEntry(raw) {
  const m = raw.match(/^---\s*\n([\s\S]*?)\n---\s*\n?([\s\S]*)$/);
  if (!m) return null;
  const fm = {};
  for (const line of m[1].split('\n')) {
    const mm = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!mm) continue;
    const key = mm[1].trim();
    let val = mm[2].trim();
    if (val.startsWith('[') && val.endsWith(']')) {
      val = val.slice(1, -1).split(',').map((s) => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
    } else {
      val = val.replace(/^["']|["']$/g, '');
    }
    fm[key] = val;
  }
  fm.body = m[2].trim();
  return fm;
}

function listEntryFiles() {
  return fs.readdirSync(KB_DIR)
    .filter((f) => f.endsWith('.md') && !f.startsWith('_') && f !== 'INDEX.md')
    .sort();
}

function statusMark(s) {
  if (s === 'dead-end') return '&#9940; dead-end';
  if (s === 'stale-able') return '&#9888; stale-able';
  return '&#9989; verified';
}

function writeHuman(entries) {
  const byTopic = {};
  for (const e of entries) (byTopic[e.topic || 'General'] || (byTopic[e.topic || 'General'] = [])).push(e);
  const topics = Object.keys(byTopic).sort();

  let out = '';
  out += '# BoldLine OS - Knowledge Index\n\n';
  out += '> **AUTO-GENERATED by `knowledge/build-index.cjs` - do NOT hand-edit this file.**\n';
  out += '> Edit the task-keyed entries in `knowledge/` and re-run `node knowledge/build-index.cjs`.\n';
  out += '>\n';
  out += '> This is the slim, human-browsable index of BoldLine\'s memory. The full detail lives in\n';
  out += `> ${entries.length} task-keyed entries under \`knowledge/\`. They surface automatically via the\n`;
  out += '> recall hook when a prompt matches, so Claude no longer bulk-reads this whole file every session.\n';
  out += '> To read the detail on any topic, open just its entry (linked below).\n\n';
  out += `**${entries.length} entries.** Legend: &#9989; verified &middot; &#9888; stale-able (may have drifted, re-check) &middot; &#9940; dead-end (tried and failed - do not retry).\n\n`;

  for (const t of topics) {
    out += `## ${t}\n\n`;
    for (const e of byTopic[t].slice().sort((a, b) => a.name.localeCompare(b.name))) {
      out += `- **[${e.name}](../${e.file})** &mdash; ${statusMark(e.status)}${e.verified ? ` &middot; ${e.verified}` : ''}  \n`;
      out += `  ${e.summary}  \n`;
      out += `  <sub>*task:* ${e.task} &nbsp;|&nbsp; *keywords:* ${(e.keywords || []).join(', ')}</sub>\n`;
    }
    out += '\n';
  }
  fs.writeFileSync(HUMAN_INDEX, out);
}

function main() {
  const files = listEntryFiles();
  const entries = [];
  for (const f of files) {
    let raw;
    try { raw = fs.readFileSync(path.join(KB_DIR, f), 'utf8'); } catch { continue; }
    const fm = parseEntry(raw);
    if (!fm) { console.warn('  skip (no frontmatter):', f); continue; }
    const kws = Array.isArray(fm.keywords) ? fm.keywords : (fm.keywords ? [fm.keywords] : []);
    entries.push({
      name: fm.name || f.replace(/\.md$/, ''),
      file: 'knowledge/' + f,
      topic: fm.topic || 'General',
      task: fm.task || '',
      keywords: kws.map(norm),
      status: fm.status || 'verified',
      summary: fm.summary || '',
      verified: fm.verified || '',
    });
  }

  const df = {};
  for (const e of entries) for (const kw of new Set(e.keywords)) df[kw] = (df[kw] || 0) + 1;

  const index = { note: 'generated by knowledge/build-index.cjs - do not edit', N: entries.length, df, entries };
  fs.writeFileSync(INDEX_JSON, JSON.stringify(index, null, 2) + '\n');
  writeHuman(entries);

  console.log(`Indexed ${entries.length} entr${entries.length === 1 ? 'y' : 'ies'}:`);
  console.log('  -> ' + path.relative(REPO_ROOT, INDEX_JSON));
  console.log('  -> ' + path.relative(REPO_ROOT, HUMAN_INDEX));
}

main();
