#!/usr/bin/env node
'use strict';
// Rebuilds the knowledge-base index. Run this after adding or editing any
// knowledge/<slug>.md entry:  node knowledge/build-index.cjs
//
// It writes two things:
//   knowledge/_index.json   -> machine index (weighted term bags + doc-frequency) read by recall.cjs
//   docs/INTEGRATIONS.md     -> slim, human-browsable table of contents (AUTO-GENERATED)
//
// No dependencies. Never edit docs/INTEGRATIONS.md by hand -- edit the entries.

const fs = require('fs');
const path = require('path');

const KB_DIR = __dirname;
const REPO_ROOT = path.resolve(KB_DIR, '..');
const INDEX_JSON = path.join(KB_DIR, '_index.json');
const HUMAN_INDEX = path.join(REPO_ROOT, 'docs', 'INTEGRATIONS.md');

// Field weights: how strong a signal each field is for recall matching.
const W = { keyword: 3, name: 2.5, task: 2, topic: 1.5, summary: 1.5 };

// Function/filler words that carry no topical signal (kept small + generic).
const STOP = new Set(('a an and are as at be but by can cant do does doesnt done for from get gets getting got had has have how i if in into is it its make made makes need needs no not of off on or our out over per see so than that the their them then there they this to up use used using via want wants was were what when where which who why will with wont you your yours yes we us am been being also any all one via vs etc'.split(/\s+/)));

const norm = (s) => String(s == null ? '' : s).toLowerCase();

function tokens(s) {
  return norm(s).split(/[^a-z0-9]+/).filter((t) => t.length >= 3 && !STOP.has(t));
}

// --- tiny YAML-ish frontmatter parser (scalars + [a, b, c] arrays) ---
function parseEntry(raw) {
  const m = raw.match(/^---\s*\n([\s\S]*?)\n---\s*\n?([\s\S]*)$/);
  if (!m) return null;
  const fm = {};
  for (const line of m[1].split('\n')) {
    const mm = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!mm) continue;
    const key = mm[1].trim();
    let val = mm[2].trim();
    if (val.startsWith('[') && val.endsWith(']')) {
      val = val.slice(1, -1).split(',').map((s) => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
    } else {
      val = val.replace(/^["']|["']$/g, '');
    }
    fm[key] = val;
  }
  fm.body = m[2].trim();
  return fm;
}

function listEntryFiles() {
  return fs.readdirSync(KB_DIR)
    .filter((f) => f.endsWith('.md') && !f.startsWith('_') && f !== 'INDEX.md')
    .sort();
}

// Build a token -> weight bag for one entry. A token keeps the strongest
// weight of any field it appears in. Hyphenated keywords contribute both the
// whole token and its parts (so "source-order" matches "source order").
function buildTerms(e) {
  const bag = {};
  const add = (arr, w) => { for (const t of arr) if (t) bag[t] = Math.max(bag[t] || 0, w); };
  for (const kw of (e.keywords || [])) {
    const k = norm(kw);
    if (k.length >= 3 && !STOP.has(k)) add([k], W.keyword);   // whole keyword
    add(tokens(kw), W.keyword);                                // its parts
  }
  add(tokens(e.name.replace(/-/g, ' ')), W.name);
  add(tokens(e.task), W.task);
  add(tokens(e.topic), W.topic);
  add(tokens(e.summary), W.summary);
  return bag;
}

function statusMark(s) {
  if (s === 'dead-end') return '&#9940; dead-end';
  if (s === 'stale-able') return '&#9888; stale-able';
  return '&#9989; verified';
}

function writeHuman(entries) {
  const byTopic = {};
  for (const e of entries) (byTopic[e.topic || 'General'] || (byTopic[e.topic || 'General'] = [])).push(e);
  const topics = Object.keys(byTopic).sort();

  let out = '';
  out += '# BoldLine OS - Knowledge Index\n\n';
  out += '> **AUTO-GENERATED by `knowledge/build-index.cjs` - do NOT hand-edit this file.**\n';
  out += '> Edit the task-keyed entries in `knowledge/` and re-run `node knowledge/build-index.cjs`.\n';
  out += '>\n';
  out += '> This is the slim, human-browsable index of BoldLine\'s memory. The full detail lives in\n';
  out += `> ${entries.length} task-keyed entries under \`knowledge/\`. They surface automatically via the\n`;
  out += '> recall hook when a prompt matches, so Claude no longer bulk-reads this whole file every session.\n';
  out += '> To read the detail on any topic, open just its entry (linked below).\n\n';
  out += `**${entries.length} entries.** Legend: &#9989; verified &middot; &#9888; stale-able (may have drifted, re-check) &middot; &#9940; dead-end (tried and failed - do not retry).\n\n`;

  for (const t of topics) {
    out += `## ${t}\n\n`;
    for (const e of byTopic[t].slice().sort((a, b) => a.name.localeCompare(b.name))) {
      out += `- **[${e.name}](../${e.file})** &mdash; ${statusMark(e.status)}${e.verified ? ` &middot; ${e.verified}` : ''}  \n`;
      out += `  ${e.summary}  \n`;
      out += `  <sub>*task:* ${e.task} &nbsp;|&nbsp; *keywords:* ${(e.keywords || []).join(', ')}</sub>\n`;
    }
    out += '\n';
  }
  fs.writeFileSync(HUMAN_INDEX, out);
}

function main() {
  const files = listEntryFiles();
  const entries = [];
  for (const f of files) {
    let raw;
    try { raw = fs.readFileSync(path.join(KB_DIR, f), 'utf8'); } catch { continue; }
    const fm = parseEntry(raw);
    if (!fm) { console.warn('  skip (no frontmatter):', f); continue; }
    const kws = Array.isArray(fm.keywords) ? fm.keywords : (fm.keywords ? [fm.keywords] : []);
    const e = {
      name: fm.name || f.replace(/\.md$/, ''),
      file: 'knowledge/' + f,
      topic: fm.topic || 'General',
      task: fm.task || '',
      keywords: kws,
      status: fm.status || 'verified',
      summary: fm.summary || '',
      verified: fm.verified || '',
    };
    e.terms = buildTerms(e);
    entries.push(e);
  }

  // document frequency over tokens (how many entries contain each token)
  const df = {};
  for (const e of entries) for (const tok of Object.keys(e.terms)) df[tok] = (df[tok] || 0) + 1;

  const index = { note: 'generated by knowledge/build-index.cjs - do not edit', N: entries.length, df, entries };
  fs.writeFileSync(INDEX_JSON, JSON.stringify(index, null, 2) + '\n');
  writeHuman(entries);

  console.log(`Indexed ${entries.length} entr${entries.length === 1 ? 'y' : 'ies'}:`);
  console.log('  -> ' + path.relative(REPO_ROOT, INDEX_JSON));
  console.log('  -> ' + path.relative(REPO_ROOT, HUMAN_INDEX));
}

main();
