// Hand-written blog content and small wording fixes, applied by blog-autopublish (Bryson, 2026-10-07: "yes to
// both" on fixing two lines in live posts and writing posts only BoldLine could write).
//
// BLOG_EDITS: exact find/replace on a published post's body. Idempotent: once the old words are gone it does nothing.
// BLOG_SEED: new posts inserted as SCHEDULED DRAFTS, one per open Monday 8am Phoenix slot (the one-per-week rule),
// so Bryson can read and edit each in the OS before it goes out. A slug that exists in any state, deleted included,
// is never inserted again, so deleting one in the OS is final.
//
// Voice rules (CLAUDE.md "Nothing may read as AI-written"): no dashes joining sentences, no parentheses, no
// "it's not X, it's Y", no invented clients or results. Facts only from BLOG_FACTS and the live site.

export const BLOG_EDITS = [
  {
    slug: "should-you-pause-your-ads-on-weekends-and-holidays",
    find: `Here's a question we get from almost every new client: "Should I turn my ads off when we're closed?"`,
    replace: `It's one of the first things a business owner asks about ads: "Should I turn my ads off when we're closed?"`,
  },
  {
    slug: "google-ads-vs-meta-ads",
    find: `<h2>The real question isn't "which platform", it's "which behavior"</h2>`,
    replace: `<h2>Start with how your customers buy</h2>`,
  },
];

const html = (...lines) => lines.join("\n");

export const BLOG_SEED = [
  {
    slug: "what-a-1500-website-gets-you",
    title: "What a $1,500 Website Gets You, and What Costs More",
    category: "Websites",
    excerpt: "Website quotes run from a few hundred dollars to tens of thousands. Here's what a $1,500 build should include, and where the bigger price tags actually go.",
    meta_description: "What a $1,500 small business website should include, what costs more, and how to tell if a quote is fair before you pay it.",
    read_minutes: 6,
    body_html: html(
      `<p>Ask five people what a website costs and you'll hear five numbers. A nephew who knows some design will do it for $300. A local agency quotes $12,000. A template site costs $16 a month and your Saturday. All three can be the right answer, which is exactly why the question is so hard to answer for yourself.</p>`,
      `<p>So instead of a range, here's a specific price and what it buys. Ours is $1,500 to build and $100 a month after that. I'll walk through what's in that number, what isn't, and what you'd be paying for if someone quotes you five times as much.</p>`,
      `<h2>What the $1,500 covers</h2>`,
      `<p>A website for a service business has one job. Someone lands on it, decides you're the right people, and calls or fills out the form. Everything in the build should serve that job.</p>`,
      `<ul>`,
      `<li><strong>Five pages written for your business.</strong> Home, services, about, reviews and contact. The words are written for you, from what you tell us about your customers, so you aren't staring at an empty box trying to describe yourself.</li>`,
      `<li><strong>A design you pick from three.</strong> You see your own business in three different modern designs and choose the one that feels like you.</li>`,
      `<li><strong>Built for a phone first.</strong> Most people who find a service business are holding a phone, often with one hand. Buttons are big, the number is one tap away, and the page loads fast on a weak signal.</li>`,
      `<li><strong>Motion that doesn't cost speed.</strong> The animations load after the page is usable and switch off on slow phones, so the site feels current without making anyone wait.</li>`,
      `<li><strong>A contact form that actually reaches you.</strong> Every enquiry arrives right away, with where the person came from attached.</li>`,
      `</ul>`,
      `<p>You can pay all of it up front, or half to start and half before it goes live. The second half is due before launch, so you've seen the finished site before you pay the rest.</p>`,
      `<h2>What the $100 a month is for</h2>`,
      `<p>A website isn't a one time purchase in the way a brochure is. It sits on a server that has to stay up, stay secure and keep its certificate current, or browsers start warning people away from it. The monthly fee covers hosting, security, keeping it running, and up to two small edits a month. New hours, a new service, a price change, a fresh photo.</p>`,
      `<p>That last part matters more than it sounds. Most small business sites go stale because changing them is a hassle. When a change is one message away, the site stays true.</p>`,
      `<h2>Where a $5,000 or $15,000 quote goes</h2>`,
      `<p>Bigger quotes aren't automatically padded. They usually pay for things a lot of service businesses don't need yet.</p>`,
      `<ul>`,
      `<li><strong>Custom photography and video.</strong> A crew at your shop for a day. Worth it for some brands, and something you can add later.</li>`,
      `<li><strong>A lot more pages.</strong> A page for every service in every city, built for search. Useful at scale, and a big writing job.</li>`,
      `<li><strong>Software built into the site.</strong> Online booking that talks to your scheduling system, quotes that price themselves, customer logins.</li>`,
      `<li><strong>Brand work.</strong> A new logo, colors and a style guide before the site is even started.</li>`,
      `</ul>`,
      `<p>If a quote is five times higher, ask which of these you're getting. If the answer is none of them, you're paying for the agency's overhead.</p>`,
      `<h2>Questions to ask before you pay anyone</h2>`,
      `<ul>`,
      `<li><strong>Do I own the domain?</strong> The web address should be registered in your name. If the person building the site owns it, leaving them gets messy.</li>`,
      `<li><strong>What happens if I leave?</strong> You should get a copy of your pages and images, and the hand-off shouldn't depend on whether you owe anything.</li>`,
      `<li><strong>Who writes the words?</strong> Plenty of builds hand you an empty template and call it a website.</li>`,
      `<li><strong>How do enquiries reach me?</strong> If the answer is "check the inbox on the site", that's a lead you'll find three days late.</li>`,
      `</ul>`,
      `<blockquote>A website doesn't need to be expensive. It needs to make calling you the easiest thing on the page.</blockquote>`,
      `<p>If you want to see what $1,500 looks like before you decide anything, click through one of our sample sites. It's a full site for a made-up business, built the same way we'd build yours.</p>`,
    ),
  },
  {
    slug: "how-we-built-a-pool-company-website",
    title: "We Built a Pool Company's Website. Here's Every Decision.",
    category: "Websites",
    excerpt: "A walk through the sample site we built for a made-up Phoenix pool company: what's on the first screen, where the buttons go, and why each choice was made.",
    meta_description: "Every design decision behind a service business website, explained using the sample pool company site BoldLine built.",
    read_minutes: 7,
    body_html: html(
      `<p>Saguaro Pool Co. doesn't exist. We made it up so we'd have a real business to build a website for and show people, without putting a client's site on display. It's a custom pool company in Phoenix, and it gets the same treatment a paying client would.</p>`,
      `<p>Here's every decision that went into it, in the order a visitor meets them. If you run a service business, almost all of it applies to you.</p>`,
      `<h2>The first screen does three jobs</h2>`,
      `<p>Someone landing on a pool company's site wants to know three things almost instantly. Is this the kind of company I'm looking for, do they look like they'd do good work, and how do I reach them. The first screen answers all three before anyone scrolls.</p>`,
      `<p>The headline says what they get: "Your backyard, finished." Not the company's history and not a slogan about passion. A short line under it says who they are and what they do, and two buttons sit right below. One books a design visit. The other shows the services.</p>`,
      `<p>The phone number is in the top bar on every page. On a phone, a call button stays pinned to the bottom of the screen the whole way down, so the visitor never has to hunt for it.</p>`,
      `<h2>Why the button says "Book a design visit"</h2>`,
      `<p>"Contact us" is the most common button on the internet and one of the weakest. It asks the visitor to start a vague conversation. "Book a design visit" tells them exactly what happens next and makes it sound like something they'd want, which for a pool company is someone coming out to look at their yard.</p>`,
      `<p>Every business has its own version of this. A detailer books a detail. A handyman gets a quote. The words on the button should name the first real step.</p>`,
      `<h2>Motion, and when to leave it out</h2>`,
      `<p>The pool site moves. Water ripples behind the headline, sections ease in as you scroll, and the service cards slide past. It's there because a site that feels current makes the business feel current, and people do notice.</p>`,
      `<p>But all of it loads after the page is already usable. On an older phone, a slow connection, or for anyone who has asked their phone to reduce motion, the effects switch off and the page just works. A fancy site that takes six seconds to appear loses more callers than a plain one.</p>`,
      `<h2>Services, written the way customers search</h2>`,
      `<p>The services page lists new pools, remodels, and spas and water features. Each one gets a plain description of what's included and who it's for. The wording matches what people actually type into Google, so "pool remodel" rather than something clever.</p>`,
      `<p>The pictures are stock photos for now, because the business is made up. With a real client, their own photos go in the moment they upload them. Real jobs beat beautiful stock every time, and they're never passed off as anyone else's work.</p>`,
      `<h2>The contact page asks for less</h2>`,
      `<ul>`,
      `<li><strong>Name, phone and a short note.</strong> Every extra field costs enquiries.</li>`,
      `<li><strong>The phone number again, tappable.</strong> Some people will always rather call.</li>`,
      `<li><strong>What happens next.</strong> One line saying when they'll hear back, so the form doesn't feel like it disappears into a void.</li>`,
      `</ul>`,
      `<p>When the form is sent, the business hears about it straight away, along with where the visitor came from. That last part is how you find out which of your marketing is actually working.</p>`,
      `<h2>Three designs, one business</h2>`,
      `<p>The same pool company exists in three designs: a bright, bold one, a darker one with full screen water behind it, and a calm editorial one. Same words, same pages. Clients pick from their own business in all three, which is a much easier decision than choosing from a gallery of strangers.</p>`,
      `<blockquote>Every choice on the site answers one question: does this make it easier for the right person to call?</blockquote>`,
      `<p>You can click through all of it yourself. The sample site is live, every page works, and you can switch between the three designs from the bar at the top.</p>`,
    ),
  },
  {
    slug: "how-car-detailers-get-more-booked-jobs-from-google",
    title: "How Car Detailers Can Get More Booked Jobs From Google",
    category: "Trades",
    excerpt: "The searches detailing customers actually type, what your Google listing and website need to show, and how to turn a click into a booked detail.",
    meta_description: "A practical guide for mobile and shop car detailers on getting more booked jobs from Google search, ads and your website.",
    read_minutes: 6,
    body_html: html(
      `<p>Detailing is a strange business to market. The work is visual and people love seeing it, but the moment someone actually needs a detail, they don't scroll Instagram. They pick up their phone and search. Whoever shows up well in that moment gets the job.</p>`,
      `<p>Here's how to be that detailer, in the order a customer finds you.</p>`,
      `<h2>Know what your customers type</h2>`,
      `<p>Detailing searches split into a few clear groups, and each one wants something different.</p>`,
      `<ul>`,
      `<li><strong>"Mobile detailing near me".</strong> They want someone to come to them, soon. Speed and convenience win.</li>`,
      `<li><strong>"Ceramic coating cost".</strong> A bigger purchase, researched. They want to understand the price before they call.</li>`,
      `<li><strong>"Interior car cleaning" or "odor removal".</strong> A specific problem they want gone. Show that you fix exactly that.</li>`,
      `<li><strong>"Paint correction".</strong> Enthusiasts. They'll judge your before and after photos harder than anyone.</li>`,
      `</ul>`,
      `<p>If you run Google ads, these should be separate ad groups with their own ads, each sending people to a page that matches. A ceramic coating shopper landing on a cheap wash price will leave.</p>`,
      `<h2>Your Google listing is the first page they see</h2>`,
      `<p>For "near me" searches, the map listings usually show up before any website. Keep yours complete: the right service area, real hours, every service listed, and photos you add regularly. Before and after shots do more work here than anywhere else.</p>`,
      `<p>Reviews carry a lot of weight in this trade. Ask every happy customer, and make it easy by sending the link the same day while the car still looks perfect.</p>`,
      `<h2>What the website has to show in five seconds</h2>`,
      `<ul>`,
      `<li><strong>Where you work.</strong> Mobile, shop, or both, and the areas you cover.</li>`,
      `<li><strong>What it costs, roughly.</strong> Starting prices for your main packages. People who can't find any price often assume it's too much.</li>`,
      `<li><strong>Your best work.</strong> A few strong before and after photos near the top.</li>`,
      `<li><strong>One clear next step.</strong> Book a detail, or get a quote. A tappable phone number as the backup.</li>`,
      `</ul>`,
      `<p>Most detailers lose bookings on the website, not in the ad. The click happened, the interest was real, and the page made it hard to act.</p>`,
      `<h2>Make the offer worth stopping for</h2>`,
      `<p>"Professional detailing" describes every detailer in town. Give people a reason to pick you today. A first time interior and exterior package at a set price. A free headlight restoration with any full detail. A maintenance plan for people who want the car to stay clean.</p>`,
      `<p>The offer should be easy to understand in one line and easy to say yes to on a phone.</p>`,
      `<h2>Answer fast</h2>`,
      `<p>Someone booking a detail usually contacts two or three businesses at once. The first one to reply tends to get the job. If you're under a car all day, that's a real problem, and it's worth setting up so every enquiry reaches your phone the second it comes in, with an instant text back telling them you'll call shortly.</p>`,
      `<blockquote>The detailer who shows up clearly, prices honestly and answers first will win more jobs than the one with the best work.</blockquote>`,
      `<p>If you want to see how all of this fits together, our sample detailing site shows the layout, the offer and the booking flow on a real page.</p>`,
    ),
  },
  {
    slug: "how-we-trace-every-call-back-to-the-ad",
    title: "How We Trace Every Call Back to the Ad That Caused It",
    category: "Google Ads",
    excerpt: "Your ad dashboard shows clicks and totals. It doesn't tell you which ad made the phone ring. Here's how call and form tracking closes that gap.",
    meta_description: "How call tracking and form tracking connect each phone call and enquiry to the exact Google or Meta ad that caused it.",
    read_minutes: 6,
    body_html: html(
      `<p>Open any ad dashboard and you'll find plenty of numbers. Impressions, clicks, cost per click, maybe a conversion count. What you won't find is the thing you actually care about: which ads made your phone ring, and whether those calls turned into paying jobs.</p>`,
      `<p>That gap is where a lot of ad money gets wasted. If you can't tell which ad brought in the customer who spent $4,000, you can't spend more on it. Here's how we close the gap for every call and form.</p>`,
      `<h2>Every visit remembers where it came from</h2>`,
      `<p>When someone clicks an ad, Google or Meta adds a small code to the address of the page they land on. Most websites ignore it. Ours keep it.</p>`,
      `<p>The landing page notes that code along with a few other details: which ad campaign, whether they came from a search or a social feed, and which page they first saw. When that person fills out the form, all of it travels with their enquiry. So instead of "a new lead", the lead arrives saying "came from a Google search ad".</p>`,
      `<h2>Calls get their own number</h2>`,
      `<p>Forms are the easy part. Phone calls are harder, because nothing about a ringing phone says where the caller found you.</p>`,
      `<p>So the ads and the landing page show a dedicated tracking number. It forwards straight to your real phone, so you answer the way you always do and the caller notices nothing. But every call to that number is logged as a lead, with the caller's number, the time and the source, before your phone even rings.</p>`,
      `<ul>`,
      `<li><strong>You keep your real number.</strong> The tracking number just forwards to it.</li>`,
      `<li><strong>Nothing changes for the caller.</strong> It's a normal local number.</li>`,
      `<li><strong>Every call is counted.</strong> Including the ones you miss, which is often the most useful number of all.</li>`,
      `</ul>`,
      `<h2>Telling Google which leads were worth having</h2>`,
      `<p>Here's where it gets more valuable than a report. A form fill and a paying customer are not worth the same, and the ad platforms can be told the difference.</p>`,
      `<p>When a lead turns out to be a real, qualified prospect, that's sent back to Google tied to the original click. Same again when they become a paying customer, even weeks later. Google's bidding then learns to chase the kind of person who actually buys, rather than the kind who fills out forms. A form fill is measured, but it's never what the bidding is told to chase.</p>`,
      `<h2>What this changes for you</h2>`,
      `<ul>`,
      `<li><strong>You can see which ads pay.</strong> Not which ads get clicks. Which ones bring in jobs.</li>`,
      `<li><strong>Budget moves to what works.</strong> Money shifts away from ads that produce calls nobody wants.</li>`,
      `<li><strong>Reports make sense.</strong> A plain English summary of what came in and from where, instead of a spreadsheet of clicks.</li>`,
      `</ul>`,
      `<blockquote>If you can't trace a customer back to the ad that found them, you're guessing with real money.</blockquote>`,
      `<p>None of this needs anything from you day to day. It's set up once, before the ads go live. If you're running ads now and can't say which ones bring in your best customers, the Free Lead-Leak Check is a good place to start.</p>`,
    ),
  },
];
